apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-client-y2ha
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-client-y2ha
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-client-y2ha
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwars-client-y2ha
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwars-client-y2ha
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eshortis-tenant/shipwars-game-server/shipwars-client-y2ha@sha256:e58dd028039330997c81c910386bd3717af9654584f739327764956e4e5d4640
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8484
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
status: {}
