apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: shipwars-move-server-fhia
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eshortis-tenant/shipwars-game-server/shipwars-move-server-fhia@sha256:fd1d696a27cdea3fd62355ff3ac62c70eefe4cbf53ee754ccd6d0c20ee6364be
        name: container-image
        resources: {}
status: {}
