apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: shipwars-bots-ulxq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eshortis-tenant/shipwars-game-server/shipwars-bots-ulxq@sha256:98d1be2a2f5dd6a9e16105fbd38005b1a0bb2e3180ff0ff1f0da27973780d002
        name: container-image
        resources: {}
status: {}
