apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-move-server-fhia
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-move-server-fhia
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-move-server-fhia
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwars-move-server-fhia
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwars-move-server-fhia
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eshortis-tenant/shipwars-game-server/shipwars-move-server-fhia@sha256:a68ca85988c90e57cfc86a64685cd003702cd182782c7c2e699f59da02585607
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
status: {}
