apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: shipwars-game-server-gubq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eshortis-tenant/shipwars-game-server/shipwars-game-server-gubq@sha256:ab2a63db5f889e60d6735f33d9aff7ee19b20aa08e026282a4e1de186be5f87d
        name: container-image
        resources: {}
status: {}
