apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-game-server-gubq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-game-server-gubq
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-game-server-gubqxjas
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: shipwars-game-server-gubq
    weight: 100
status: {}
