apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-bots-el1s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-bots-el1s
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-bots-el1s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwars-bots-el1s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwars-bots-el1s
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
status: {}
