apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-bots-ulxq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-bots-ulxq
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-bots-ulxq
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: shipwars-bots-ulxq
status:
  loadBalancer: {}
