apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-game-server-gubq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-game-server-gubq
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-game-server-gubq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwars-game-server-gubq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwars-game-server-gubq
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: stonesoup
        - name: AI_AGENT_SERVER_URL
          value: https://shipwars-bots-ulxq-eshortis-tenant.apps.stone-prd-m01.84db.p1.openshiftapps.com/
        - name: AI_AGENT_WSS_URL
          value: wss://shipwars-game-server-gubq-eshortis-tenant.apps.stone-prd-m01.84db.p1.openshiftapps.com/shipwars/game
        image: quay.io/redhat-user-workloads/eshortis-tenant/shipwars-game-server/shipwars-game-server-gubq@sha256:c0fa573b9a42c15cd0884e8d0f600c087d503d93092e82feecbc15ac89d57df8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
status: {}
