apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-game-server-gubq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-game-server-gubq
    app.kubernetes.io/part-of: shipwars-game-server
  name: shipwars-game-server-gubq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwars-game-server-gubq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwars-game-server-gubq
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: stonesoup
        image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
status: {}
